# Generated by Django 4.2.19 on 2025-02-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modified_at',
        ),
    ]
